# -*- coding: utf-8 -*-
"""AIO2026 CONQUER MODULE 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAm6bGiGLCXhqJXOP0wFLvtm72gu22Pj?usp=sharing

# AIO2026 CONQUER MODULE 1
## Similarity Matching Methods for Images and Texts
"""

# Install and setup dependencies
# !pip install datasets transformers scikit-learn matplotlib pandas torch torchvision

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torchvision.transforms as T
from torchvision.models import resnet50, ResNet50_Weights
from transformers import CLIPProcessor, CLIPModel
from datasets import load_dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.manifold import TSNE
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")

"""### 1. Google Drive Mounting"""

try:
    from google.colab import drive

    drive.mount("/content/drive")
    SAVE_DIR = "/content/drive/MyDrive/AIO2026_Conquer_Module01"
    os.makedirs(SAVE_DIR, exist_ok=True)
except ImportError:
    SAVE_DIR = "./"

# Device configuration (use GPU if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# device = torch.device('cpu')

"""### 2. Pure Consine Similarity helper function"""


def cosine_sim(a, b):
    a = np.array(a, dtype=float).flatten()
    b = np.array(b, dtype=float).flatten()
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    # (1e-8) is added to prevent division by zero
    return dot_product / (norm_a * norm_b + 1e-8)


"""### 3. Prepare data"""

dataset = load_dataset("jxie/flickr8k")


# Helper function to grab the first valid caption
def extract_caption(item):
    for i in range(5):
        key = f"caption_{i}"
        if key in item and item[key] and len(str(item[key])) > 5:
            return item[key]
    return "A photo of something."


# load train set (6000 images)
# this train set is only for linear regression
# for finding the maping weights "W" of method 2
train_images = []
train_captions = []
for item in dataset["train"]:
    if "image" in item:
        train_images.append(item["image"].convert("RGB"))
        train_captions.append(extract_caption(item))

# load test set (1000 images)
test_images = []
test_captions = []
for item in dataset["test"]:
    if "image" in item:
        test_images.append(item["image"].convert("RGB"))
        test_captions.append(extract_caption(item))

"""### 4. Feature extraction"""

# 1. ResNet50 for Image Features
resnet = resnet50(weights=ResNet50_Weights.DEFAULT)
# Remove the final classification layer (fc) to get the raw 2048-dim feature vector
resnet.fc = torch.nn.Identity()
resnet = resnet.to(device).eval()

resnet_transforms = T.Compose(
    [
        T.Resize(256),
        T.CenterCrop(224),
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
)


# Helper function to extract ResNet features
def extract_resnet_features(image_list):
    features = []
    with torch.no_grad():
        for img in image_list:
            img_tensor = resnet_transforms(img).unsqueeze(0).to(device)
            feature = resnet(img_tensor).cpu().numpy().flatten()
            features.append(feature)
    return np.array(features)


# Exract ResNet for both Train and Test sets
train_resnet_features = extract_resnet_features(train_images)
test_resnet_features = extract_resnet_features(test_images)

# 2. TF-IDF for Text Features
vectorizer = TfidfVectorizer(max_features=500)
# IMPORTANT! FIT on train to build vocab, but only TRASNFORM test
train_tfidf_features = vectorizer.fit_transform(train_captions).toarray()
test_tfidf_features = vectorizer.transform(test_captions).toarray()

# 3. Clip for both modalities
clip_model_id = "openai/clip-vit-base-patch32"
clip_processor = CLIPProcessor.from_pretrained(clip_model_id)
clip_model = CLIPModel.from_pretrained(clip_model_id).to(device).eval()


# Helper function to extract CLIP features
def extract_clip_features(image_list, caption_list):
    img_features = []
    txt_features = []
    with torch.no_grad():
        for img, cap in zip(image_list, caption_list):
            inputs = clip_processor(
                text=[cap], images=[img], return_tensors="pt", padding=True
            ).to(device)
            outputs = clip_model(**inputs)

            # Normalize CLIP embeddings
            img = outputs.image_embeds
            img = img / img.norm(dim=-1, keepdim=True)

            txt = outputs.text_embeds
            txt = txt / txt.norm(dim=-1, keepdim=True)

            img_features.append(img.cpu().numpy().flatten())
            txt_features.append(txt.cpu().numpy().flatten())
    return np.array(img_features), np.array(txt_features)


# Extract for both Train and Test sets
train_clip_img_features, train_clip_txt_features = extract_clip_features(
    train_images, train_captions
)
test_clip_img_features, test_clip_txt_features = extract_clip_features(
    test_images, test_captions
)

"""### 5. Train Linear Regression for projecting the visual space into the textual space (Method 2)"""

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(
    train_resnet_features, train_tfidf_features
)  # Finding the maping weights "W"

projected_test_resnet_features = lin_reg.predict(test_resnet_features)

"""### 6. Make hard negative helper function"""


def make_hard_negative(text):
    """
    Modifies the caption by swapping key subjects to create a conceptually
    different sentence (a 'hard negative').
    """
    words = text.split()
    replacements = {
        # Animals
        "dog": "cat",
        "Dog": "Cat",
        "cat": "dog",
        "Cat": "Dog",
        "puppy": "kitten",
        "Puppy": "Kitten",
        "kitten": "puppy",
        "Kitten": "Puppy",
        # People (Gender)
        "man": "woman",
        "Man": "Woman",
        "woman": "man",
        "Woman": "Man",
        "boy": "girl",
        "Boy": "Girl",
        "girl": "boy",
        "Girl": "Boy",
        "male": "female",
        "Male": "Female",
        "female": "male",
        "Female": "Male",
        # Familial Relationships
        "father": "mother",
        "Father": "Mother",
        "mother": "father",
        "Mother": "Father",
        "son": "daughter",
        "Son": "Daughter",
        "daughter": "son",
        "Daughter": "Son",
        "husband": "wife",
        "Husband": "Wife",
        "wife": "husband",
        "Wife": "Husband",
        "brother": "sister",
        "Brother": "Sister",
        "sister": "brother",
        "Sister": "Brother",
        "grandfather": "grandmother",
        "Grandfather": "Grandmother",
        "grandmother": "grandfather",
        "Grandmother": "Grandfather",
        "grandson": "granddaughter",
        "Grandson": "Granddaughter",
        "granddaughter": "grandson",
        "Granddaughter": "Grandson",
        "uncle": "aunt",
        "Uncle": "Aunt",
        "aunt": "uncle",
        "Aunt": "Uncle",
        "nephew": "niece",
        "Nephew": "Niece",
        "niece": "nephew",
        "Niece": "Nephew",
        # Pronouns
        "he": "she",
        "He": "She",
        "she": "he",
        "She": "He",
        "him": "her",
        "Him": "Her",
        "her": "him",
        "Her": "Him",
        "his": "her",
        "His": "Her",
        "himself": "herself",
        "Himself": "Herself",
        "herself": "himself",
        "Herself": "Himself",
        # Professions & Titles
        "actor": "actress",
        "Actor": "Actress",
        "actress": "actor",
        "Actress": "Actor",
        "waiter": "waitress",
        "Waiter": "Waitress",
        "waitress": "waiter",
        "Waitress": "Waiter",
        "king": "queen",
        "King": "Queen",
        "queen": "king",
        "Queen": "King",
        "prince": "princess",
        "Prince": "Princess",
        "princess": "prince",
        "Princess": "Prince",
        # Actions/Verbs
        "running": "standing",
        "Running": "Standing",
        "standing": "running",
        "Standing": "Running",
        "walking": "sitting",
        "Walking": "Sitting",
        "sitting": "walking",
        "Sitting": "Walking",
        "jumping": "sleeping",
        "Jumping": "Sleeping",
        # Locations
        "beach": "street",
        "Beach": "Street",
        "street": "beach",
        "Street": "Beach",
        "grass": "pavement",
        "Grass": "Pavement",
        "field": "room",
        "Field": "Room",
        # Counts
        "one": "two",
        "One": "Two",
        "two": "one",
        "Two": "One",
        "group": "individual",
        "Group": "Individual",
    }
    new_words = []
    modified = False
    for w in words:
        clean_w = w.strip(".,!?\"'")
        if clean_w in replacements:
            new_words.append(w.replace(clean_w, replacements[clean_w]))
            modified = True
        else:
            new_words.append(w)
    return " ".join(new_words), modified


"""### 7. Evaluate"""


def calculate_retrieval_metrics(img_features, txt_features):
    num_samples = len(img_features)

    # L2 Normalize features for cosine similarity
    # Added 1e-8 to prevent division by zero
    img_norm = img_features / (
        np.linalg.norm(img_features, axis=1, keepdims=True) + 1e-8
    )
    txt_norm = txt_features / (
        np.linalg.norm(txt_features, axis=1, keepdims=True) + 1e-8
    )

    # Compute all pairwise cosine similarities at once (Matrix Multiplication)
    sim_matrix = np.dot(img_norm, txt_norm.T)

    # Sort indices in descending order of similarity
    sorted_indices = np.argsort(sim_matrix, axis=1)[:, ::-1]

    # Find the rank of the ground truth (the diagonal where j == i)
    ground_truth_positions = np.arange(num_samples).reshape(num_samples, 1)
    ranks = np.where(sorted_indices == ground_truth_positions)[1] + 1

    recall_at_1 = np.sum(ranks == 1) / num_samples
    recall_at_5 = np.sum(ranks <= 5) / num_samples
    mrr = np.sum(1.0 / ranks) / num_samples

    return {"R@1": recall_at_1, "R@5": recall_at_5, "MRR": mrr}


results = {
    "Method 1 (Naive Baseline)": {"pos": [], "rand": [], "hard": []},
    "Method 2 (Linear Projection)": {"pos": [], "rand": [], "hard": []},
    "Method 3 (CLIP)": {"pos": [], "rand": [], "hard": []},
}

tfidf_dim = train_tfidf_features.shape[1]
m1_test_img_features = test_resnet_features[:, :tfidf_dim]

print("Calculating cosine similarity scores...")
# Loop over the TEST set only
for i in range(len(test_images)):
    m1_img = m1_test_img_features[i]
    m1_txt = test_tfidf_features[i]

    # m2 uses the model projected on the test set
    m2_img = projected_test_resnet_features[i]
    m2_txt = test_tfidf_features[i]

    m3_img = test_clip_img_features[i]
    m3_txt = test_clip_txt_features[i]

    # 1. Positive Pair
    results["Method 1 (Naive Baseline)"]["pos"].append(cosine_sim(m1_img, m1_txt))
    results["Method 2 (Linear Projection)"]["pos"].append(cosine_sim(m2_img, m2_txt))
    results["Method 3 (CLIP)"]["pos"].append(cosine_sim(m3_img, m3_txt))

    # 2. Random Negative Pair
    j = random.choice([x for x in range(len(test_images)) if x != i])
    results["Method 1 (Naive Baseline)"]["rand"].append(
        cosine_sim(m1_img, test_tfidf_features[j])
    )
    results["Method 2 (Linear Projection)"]["rand"].append(
        cosine_sim(m2_img, test_tfidf_features[j])
    )
    results["Method 3 (CLIP)"]["rand"].append(
        cosine_sim(m3_img, test_clip_txt_features[j])
    )

    # 3. Hard Negative
    hard_cap, was_modified = make_hard_negative(test_captions[i])
    if was_modified:
        m12_hard_txt = vectorizer.transform([hard_cap]).toarray()[0]

        with torch.no_grad():
            inputs = clip_processor(
                text=[hard_cap],
                images=[test_images[i]],
                return_tensors="pt",
                padding=True,
            ).to(device)
            outputs = clip_model(**inputs)
            m3_hard_txt = outputs.text_embeds.cpu().numpy().flatten()

        results["Method 1 (Naive Baseline)"]["hard"].append(
            cosine_sim(m1_img, m12_hard_txt)
        )
        results["Method 2 (Linear Projection)"]["hard"].append(
            cosine_sim(m2_img, m12_hard_txt)
        )
        results["Method 3 (CLIP)"]["hard"].append(cosine_sim(m3_img, m3_hard_txt))

print("Calculating Retrieval Metrics (Recall/MRR)...")
retrieval_metrics = {
    "Method 1 (Naive Baseline)": calculate_retrieval_metrics(
        m1_test_img_features, test_tfidf_features
    ),
    "Method 2 (Linear Projection)": calculate_retrieval_metrics(
        projected_test_resnet_features, test_tfidf_features
    ),
    "Method 3 (CLIP)": calculate_retrieval_metrics(
        test_clip_img_features, test_clip_txt_features
    ),
}

"""### 8. Format and save results to table"""

table_data = []
for method in results.keys():
    pos_mean, pos_std = np.mean(results[method]["pos"]), np.std(results[method]["pos"])
    rand_mean, rand_std = (
        np.mean(results[method]["rand"]),
        np.std(results[method]["rand"]),
    )

    if len(results[method]["hard"]) > 0:
        hard_mean, hard_std = (
            np.mean(results[method]["hard"]),
            np.std(results[method]["hard"]),
        )
    else:
        hard_mean, hard_std = 0.0, 0.0

    ret = retrieval_metrics[method]

    table_data.append(
        {
            "Method": method,
            "Positive Pair": f"{pos_mean:.4f} ± {pos_std:.4f}",
            "Random Negative": f"{rand_mean:.4f} ± {rand_std:.4f}",
            "Hard Negative": f"{hard_mean:.4f} ± {hard_std:.4f}",
            "R@1": f"{ret['R@1']:.4f}",
            "R@5": f"{ret['R@5']:.4f}",
            "MRR": f"{ret['MRR']:.4f}",
        }
    )

df_results = pd.DataFrame(table_data)

print("\nFinal Benchmark Comparison Table")
print("=" * 137)
print(df_results.to_markdown(index=False))
print("=" * 137)

csv_path = os.path.join(SAVE_DIR, "results.csv")
df_results.to_csv(csv_path, index=False)

"""### 9. t-SNE Visualization"""

tsne_idx = min(100, len(test_images))

m2_imgs = projected_test_resnet_features[:tsne_idx]
m2_txts = test_tfidf_features[:tsne_idx]

m3_imgs = test_clip_img_features[:tsne_idx]
m3_txts = test_clip_txt_features[:tsne_idx]

m2_combined = np.vstack([m2_imgs, m2_txts])

perp = min(15, (tsne_idx * 2) // 3)

tsne_m2 = TSNE(n_components=2, perplexity=perp, random_state=42).fit_transform(
    m2_combined
)

m3_combined = np.vstack([m3_imgs, m3_txts])

tsne_m3 = TSNE(n_components=2, perplexity=perp, random_state=42).fit_transform(
    m3_combined
)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

# Method 2 (Linear Projection)
ax1.scatter(
    tsne_m2[:tsne_idx, 0],
    tsne_m2[:tsne_idx, 1],
    c="red",
    alpha=0.7,
    label="Projected Images",
)

ax1.scatter(
    tsne_m2[tsne_idx:, 0],
    tsne_m2[tsne_idx:, 1],
    c="blue",
    alpha=0.7,
    label="TF-IDF Captions",
)

ax1.set_title("Method 2 (Linear Projection)")
ax1.legend()


# Method 3 (Pair Alignment)
colors = plt.cm.tab20(np.linspace(0, 1, tsne_idx))

for i in range(tsne_idx):
    # Image
    ax2.scatter(tsne_m3[i, 0], tsne_m3[i, 1], color=colors[i], marker="o", s=45)

    # Caption
    ax2.scatter(
        tsne_m3[tsne_idx + i, 0],
        tsne_m3[tsne_idx + i, 1],
        color=colors[i],
        marker="^",
        s=45,
    )

    # Connection
    ax2.plot(
        [tsne_m3[i, 0], tsne_m3[tsne_idx + i, 0]],
        [tsne_m3[i, 1], tsne_m3[tsne_idx + i, 1]],
        color=colors[i],
        alpha=0.30,
    )

ax2.set_title("Method 3 (CLIP Pair Alignment)")

plt.tight_layout()
plt.show()

"""### 10. CLIP Similarity Heatmap"""

heatmap_size = 30

similarity_matrix = np.zeros((heatmap_size, heatmap_size))

for i in range(heatmap_size):
    for j in range(heatmap_size):
        similarity_matrix[i, j] = cosine_sim(
            test_clip_img_features[i], test_clip_txt_features[j]
        )

plt.figure(figsize=(8, 7))

plt.imshow(similarity_matrix, cmap="viridis")

plt.colorbar(label="Cosine Similarity")

plt.xlabel("Caption Index")
plt.ylabel("Image Index")

plt.title("CLIP Image-Text Similarity Matrix")

plt.show()

"""### 11. Top-K Retrieval Qualitative Demo

"""

print("=" * 90)
print("TOP-K RETRIEVAL QUALITATIVE DEMO (CLIP MODEL - TEST SET)")
print("=" * 90)

num_test = len(test_images)

# Best retrieval example
best_idx = np.argmax(results["Method 3 (CLIP)"]["pos"])

# Random example
random_idx = random.randint(0, num_test - 1)

demo_indices = [best_idx, random_idx]

for idx in demo_indices:
    img_feat = test_clip_img_features[idx]

    # Compute cosine similarities
    sims = []

    for j in range(num_test):
        score = cosine_sim(img_feat, test_clip_txt_features[j])
        sims.append((j, score))

    sims.sort(key=lambda x: x[1], reverse=True)

    # Text output

    print(f"\nQuery Image Index: {idx}")
    print(f'Ground Truth Caption:\n"{test_captions[idx]}"')

    # Visualization

    fig, axes = plt.subplots(1, 4, figsize=(18, 5))

    # Query image
    axes[0].imshow(test_images[idx])
    axes[0].set_title("Query Image")
    axes[0].axis("off")

    # Top-3 retrieved captions/images
    for k, (j, score) in enumerate(sims[:3]):
        axes[k + 1].imshow(test_images[j])

        axes[k + 1].set_title(f"Rank {k + 1}\nScore={score:.3f}")

        axes[k + 1].set_xlabel(test_captions[j], fontsize=8)

        axes[k + 1].axis("off")

    plt.tight_layout()
    plt.show()

    # Also print captions

    print("\nTop 3 Retrieved Captions")

    for rank, (j, score) in enumerate(sims[:3]):
        print(f"{rank + 1}. Score={score:.4f}\n   {test_captions[j]}")

    print("-" * 90)

"""### 12. Error Analysis (Failure Cases)"""
print("=" * 90)
print("ERROR ANALYSIS (CLIP MODEL)")
print("=" * 90)

# Find a case where rank > 1
failure_idx = -1
for i in range(num_test):
    img_feat = test_clip_img_features[i]
    sims = []
    for j in range(num_test):
        sims.append((j, cosine_sim(img_feat, test_clip_txt_features[j])))
    sims.sort(key=lambda x: x[1], reverse=True)
    rank = 0
    for r, (j, score) in enumerate(sims):
        if j == i:
            rank = r + 1
            break
    if rank > 3:  # Find a tough one
        failure_idx = i
        break

if failure_idx != -1:
    print(f"\nQuery Image Index (Failure Case): {failure_idx}")
    print(f'Ground Truth Caption (Rank {rank}):\n"{test_captions[failure_idx]}"')

    img_feat = test_clip_img_features[failure_idx]
    sims = []
    for j in range(num_test):
        sims.append((j, cosine_sim(img_feat, test_clip_txt_features[j])))
    sims.sort(key=lambda x: x[1], reverse=True)

    print("\nTop 3 Retrieved Captions (Incorrectly ranked higher):")
    for r, (j, score) in enumerate(sims[:3]):
        print(f"{r + 1}. Score={score:.4f} \n   {test_captions[j]}")

    fig, axes = plt.subplots(1, 4, figsize=(18, 5))
    axes[0].imshow(test_images[failure_idx])
    axes[0].set_title("Query Image (Failure)")
    axes[0].axis("off")

    for k, (j, score) in enumerate(sims[:3]):
        axes[k + 1].imshow(test_images[j])
        axes[k + 1].set_title(f"Rank {k + 1}\nScore={score:.3f}")
        axes[k + 1].set_xlabel(
            test_captions[j][:50] + "...", fontsize=8
        )  # truncated for visual
        axes[k + 1].axis("off")
    plt.tight_layout()
    plt.show()

print("-" * 90)

"""### 13. Ablation Study: TF-IDF Vocabulary Size"""
print("=" * 90)
print("ABLATION STUDY: TF-IDF VOCABULARY SIZE")
print("=" * 90)

vocab_sizes = [500, 1000, 2000]
ablation_results = []

for vs in vocab_sizes:
    print(f"Testing vocab size: {vs}...")
    vec = TfidfVectorizer(max_features=vs)
    tr_tfidf = vec.fit_transform(train_captions).toarray()
    te_tfidf = vec.transform(test_captions).toarray()

    lin_r = LinearRegression()
    lin_r.fit(train_resnet_features, tr_tfidf)
    proj_te_resnet = lin_r.predict(test_resnet_features)

    ret_metrics = calculate_retrieval_metrics(proj_te_resnet, te_tfidf)
    ablation_results.append(
        {
            "Vocab Size": vs,
            "Recall@1": f"{ret_metrics['R@1']:.4f}",
            "Recall@5": f"{ret_metrics['R@5']:.4f}",
            "MRR": f"{ret_metrics['MRR']:.4f}",
        }
    )

df_ablation = pd.DataFrame(ablation_results)
print("\nAblation Results (Method 2 - Linear Projection):")
print(df_ablation.to_markdown(index=False))
